## Actividad 1: 

* Francelio Uriel Rodriguez Garcia - A01352663 
* Juan Pablo Valenzuela Dorado - A00227321
* Juan Pablo Bernal Lafarga - A01742342
* Alfredo Murillo Madrigal - A01641791


# Ejercicio 1

1. Debido a que la composición de funciones lineales es también una función lineal:

    Considerando una función lineal
$$
f(x)=a x+b
$$
donde $a$ y $b$ son constantes:
$$
\begin{aligned}
& f(f(x))=f(a x+b)=a(a x+b)+b =a^2 x+a b+b
\end{aligned}
$$
$$
\begin{aligned}
& \text { Si } c=a^2 \text { y } d=a b+b \\
& f(f(x))=c x+d
\end{aligned}
$$

Por lo tanto, si todas las funciones de activación de las neuronas son lineales, la salida va a ser una función lineal.

# Ejercicio 2


# Ejercicio 3

1. Ajusta un modelo perceptrón multicapa para este conjunto de datos (misterious_data_1) con dos clases y evalúa su rendimiento con validación cruzada.

In [1]:
import numpy as np
import pandas as pd

from sklearn import datasets
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import classification_report
from sklearn.neural_network import MLPClassifier

from keras.models import Sequential
from keras.layers import Dense
from tensorflow.python.keras.utils import np_utils

# Load data
data = np.loadtxt("C:/Users/franu/Downloads/RedesNeuronales/Actividad1/misterious_data_1.txt") 
x = data[:,1:]
y = data[:,0]

# Train MLP classifier with all the available observations
clf = MLPClassifier(hidden_layer_sizes=(10, 10), max_iter=10000)  # hidden_layer_sizes controls the number of neurons of each hidden layer.
clf.fit(x, y)

# 5-fold cross-validation
n_splits=5
kf = StratifiedKFold(n_splits=n_splits, shuffle = True)

cv_y_test = []
cv_y_pred = []

for train_index, test_index in kf.split(x, y):

    # Training phase
    x_train = x[train_index, :]
    y_train = y[train_index]

    clf_i = MLPClassifier(hidden_layer_sizes=(10, 10), max_iter=10000)
    clf_i.fit(x_train, y_train)

    # Test phase
    x_test = x[test_index, :]
    y_test = y[test_index]    
    y_pred = clf_i.predict(x_test)

    cv_y_test.append(y_test)
    cv_y_pred.append(y_pred)

print(classification_report(np.concatenate(cv_y_test), np.concatenate(cv_y_pred)))

              precision    recall  f1-score   support

         1.0       0.81      0.74      0.77       264
         2.0       0.76      0.82      0.79       264

    accuracy                           0.78       528
   macro avg       0.78      0.78      0.78       528
weighted avg       0.78      0.78      0.78       528



In [2]:
from tensorflow.python.keras.utils import np_utils

data = np.loadtxt("C:/Users/franu/Downloads/RedesNeuronales/Actividad1/misterious_data_1.txt") 
x = data[:,1:]
y = data[:,0]

y[y == 1] = 0
y[y == 2] = 1

#targets = data.target_names
n_clases = len(np.unique(y))

#features = data.feature_names
n_features = x.shape[1]

# Define MLP model
clf = Sequential()
clf.add(Dense(10, input_dim=n_features, activation='relu'))
clf.add(Dense(10, activation='relu'))
clf.add(Dense(1, activation='sigmoid')) # for 2-class problems, use clf.add(Dense(1, activation='sigmoid'))

# Compile model
clf.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

# Evaluate model
kf = StratifiedKFold(n_splits=5, shuffle = True)

cv_y_test = []
cv_y_pred = []

for train_index, test_index in kf.split(x, y):

    x_train = x[train_index, :]
    y_train = y[train_index]
    #y_train_categorical = np_utils.to_categorical(y_train)

    x_test = x[test_index, :]
    y_test = y[test_index]
    #y_test_categorical = np_utils.to_categorical(y_test)

    # Training phase
    clf_cv = Sequential()
    clf_cv.add(Dense(10, input_dim=n_features, activation='relu'))
    clf_cv.add(Dense(10, activation='relu'))
    clf_cv.add(Dense(1, activation='sigmoid'))
    clf_cv.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy']) 
    clf_cv.fit(x_train, y_train, validation_data= (x_test, y_test), epochs=150, batch_size=5)    

    # Test phase
    x_test = x[test_index, :]
    y_test = y[test_index]
    y_pred = clf_cv.predict(x_test)
    y_pred = (y_pred > 0.5).astype(int) 

    cv_y_test.append(y_test)
    cv_y_pred.append(y_pred)


print(classification_report(np.concatenate(cv_y_test), np.concatenate(cv_y_pred)))

Epoch 1/150
85/85 [==============================] - 1s 5ms/step - loss: 0.8864 - accuracy: 0.4976 - val_loss: 0.7154 - val_accuracy: 0.4811
Epoch 2/150
85/85 [==============================] - 0s 3ms/step - loss: 0.6592 - accuracy: 0.5474 - val_loss: 0.6561 - val_accuracy: 0.5472
Epoch 3/150
85/85 [==============================] - 0s 2ms/step - loss: 0.5979 - accuracy: 0.6232 - val_loss: 0.6335 - val_accuracy: 0.6226
Epoch 4/150
85/85 [==============================] - 0s 2ms/step - loss: 0.5509 - accuracy: 0.7227 - val_loss: 0.6051 - val_accuracy: 0.6698
Epoch 5/150
85/85 [==============================] - 0s 2ms/step - loss: 0.5078 - accuracy: 0.7962 - val_loss: 0.5810 - val_accuracy: 0.7547
Epoch 6/150
85/85 [==============================] - 0s 2ms/step - loss: 0.4641 - accuracy: 0.8555 - val_loss: 0.5455 - val_accuracy: 0.7830
Epoch 7/150
85/85 [==============================] - 0s 2ms/step - loss: 0.4121 - accuracy: 0.8815 - val_loss: 0.5126 - val_accuracy: 0.7830
Epoch 8/150
8

2. Ajusta un modelo perceptrón multicapa para este otro conjunto de datos(misterious_data_4) de cuatro clases y evalúa su rendimiento con validación cruzada.

In [4]:
data = np.loadtxt("C:/Users/franu/Downloads/RedesNeuronales/Actividad1/misterious_data_4.txt") 
x = data[:,1:]
y = data[:,0]

# Train MLP classifier with all the available observations

clf = MLPClassifier(hidden_layer_sizes=(10, 10), max_iter=10000)  # hidden_layer_sizes controls the number of neurons of each hidden layer.
clf.fit(x, y)

# 5-fold cross-validation
n_splits=5
kf = StratifiedKFold(n_splits=n_splits, shuffle = True)

cv_y_test = []
cv_y_pred = []

for train_index, test_index in kf.split(x, y):

    # Training phase
    x_train = x[train_index, :]
    y_train = y[train_index]

    clf_i = MLPClassifier(hidden_layer_sizes=(10, 10), max_iter=10000)
    clf_i.fit(x_train, y_train)

    # Test phase
    x_test = x[test_index, :]
    y_test = y[test_index]    
    y_pred = clf_i.predict(x_test)

    cv_y_test.append(y_test)
    cv_y_pred.append(y_pred)

print(classification_report(np.concatenate(cv_y_test), np.concatenate(cv_y_pred)))

              precision    recall  f1-score   support

         1.0       0.98      1.00      0.99        64
         2.0       1.00      1.00      1.00        65
         3.0       0.88      0.92      0.90        65
         4.0       0.92      0.86      0.89        65

    accuracy                           0.95       259
   macro avg       0.95      0.95      0.95       259
weighted avg       0.95      0.95      0.95       259



In [ ]:
data = np.loadtxt("C:/Users/franu/Downloads/RedesNeuronales/Actividad1/misterious_data_4.txt") 
x = data[:,1:]
y = data[:,0]

# Convert target labels to start from 0
y = y.astype(int) - 1

#targets = data.target_names
n_clases = len(np.unique(y))

#features = data.feature_names
n_features = x.shape[1]

# Create output variables from original labels. This is required only in multiclass problems.
output_y = np_utils.to_categorical(y)   
print(output_y)

# Define MLP model
clf = Sequential()
clf.add(Dense(10, input_dim=n_features, activation='relu'))
clf.add(Dense(10, activation='relu'))
clf.add(Dense(4, activation='softmax')) # for 2-class problems, use clf.add(Dense(1, activation='sigmoid'))

# Compile model
clf.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
 
# Fit model
clf.fit(x, output_y, epochs=150, batch_size=5)

# Evaluate model
kf = StratifiedKFold(n_splits=5, shuffle = True)

cv_y_test = []
cv_y_pred = []

for train_index, test_index in kf.split(x, y):

    x_train = x[train_index, :]
    y_train = y[train_index]
    y_train_categorical = np_utils.to_categorical(y_train)

    x_test = x[test_index, :]
    y_test = y[test_index]
    y_test_categorical = np_utils.to_categorical(y_test)

    # Training phase
    clf_cv = Sequential()
    clf_cv.add(Dense(10, input_dim=n_features, activation='relu'))
    clf_cv.add(Dense(10, activation='relu'))
    clf_cv.add(Dense(4, activation='softmax'))
    clf_cv.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy']) 
    clf_cv.fit(x_train, y_train_categorical, validation_data= (x_test, y_test_categorical), epochs=150, batch_size=5)    

    # Test phase
    x_test = x[test_index, :]
    y_test = y[test_index]
    y_pred = np.argmax(clf_cv.predict(x_test), axis=-1)  

    cv_y_test.append(y_test)
    cv_y_pred.append(y_pred)


print(classification_report(np.concatenate(cv_y_test), np.concatenate(cv_y_pred)))

[[1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 ...
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]]
Epoch 1/150
52/52 [==============================] - 1s 1ms/step - loss: 0.9567 - accuracy: 0.4903
Epoch 2/150
52/52 [==============================] - 0s 1ms/step - loss: 0.6346 - accuracy: 0.6911
Epoch 3/150
52/52 [==============================] - 0s 1ms/step - loss: 0.4462 - accuracy: 0.7606
Epoch 4/150
52/52 [==============================] - 0s 1ms/step - loss: 0.2833 - accuracy: 0.9421
Epoch 5/150
52/52 [==============================] - 0s 991us/step - loss: 0.1909 - accuracy: 0.9575
Epoch 6/150
52/52 [==============================] - 0s 1ms/step - loss: 0.1488 - accuracy: 0.9498
Epoch 7/150
52/52 [==============================] - 0s 1ms/step - loss: 0.1179 - accuracy: 0.9537
Epoch 8/150
52/52 [==============================] - 0s 1ms/step - loss: 0.0898 - accuracy: 0.9653
Epoch 9/150
52/52 [==============================] - 0s 1ms/step - loss: 0.0835 - accuracy: 0.9730
Epoch 10/15

3. Para el conjunto de datos diabetes, ajusta un modelo de regresión perceptrón multicapa, y evalúa el error cuadrático medio del modelo con validación cruzada.

In [11]:
import numpy as np
from sklearn import datasets
from sklearn.model_selection import KFold
from sklearn.metrics import mean_squared_error

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Import the diabetes dataset
data = datasets.load_diabetes()
x = data.data
y = data.target

n_features = x.shape[1]

# Define MLP model
clf = Sequential()
clf.add(Dense(10, input_dim=n_features, activation='relu'))
clf.add(Dense(10, activation='relu'))
clf.add(Dense(1, activation='linear'))

# Compile model
clf.compile(loss='mean_squared_error', optimizer='adam')


kf = StratifiedKFold(n_splits=5, shuffle = True)
mse_scores = []

for train_index, test_index in kf.split(x,y):
    x_train = x[train_index, :]
    y_train = y[train_index]

    x_test = x[test_index, :]
    y_test = y[test_index]

    # Training phase
    clf.fit(x_train, y_train, epochs=150, batch_size=5)

    # Test phase
    y_pred = clf.predict(x_test)
    mse = mean_squared_error(y_test, y_pred)
    mse_scores.append(mse)


MSE = np.mean(mse_scores)
print(f'Mean Squared Error: {MSE}')


Epoch 1/150


c:\Users\franu\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\model_selection\_split.py:680: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(


71/71 [==============================] - 1s 3ms/step - loss: 29680.4824
Epoch 2/150
71/71 [==============================] - 0s 2ms/step - loss: 29401.9863
Epoch 3/150
71/71 [==============================] - 0s 2ms/step - loss: 28639.2461
Epoch 4/150
71/71 [==============================] - 0s 1ms/step - loss: 27084.5801
Epoch 5/150
71/71 [==============================] - 0s 1ms/step - loss: 24547.4609
Epoch 6/150
71/71 [==============================] - 0s 1ms/step - loss: 21112.8848
Epoch 7/150
71/71 [==============================] - 0s 1ms/step - loss: 17138.0645
Epoch 8/150
71/71 [==============================] - 0s 1ms/step - loss: 13137.2227
Epoch 9/150
71/71 [==============================] - 0s 1ms/step - loss: 9769.5537
Epoch 10/150
71/71 [==============================] - 0s 1ms/step - loss: 7309.7896
Epoch 11/150
71/71 [==============================] - 0s 1ms/step - loss: 5840.5083
Epoch 12/150
71/71 [==============================] - 0s 1ms/step - loss: 5081.1821
Epoch